[package]
authors = ["Your Name <your.email@example.com>"]
categories = ["cryptography", "authentication", "security"]
description = "A comprehensive implementation of Chaum-Pedersen Zero-Knowledge Proofs with multiple interfaces and practical applications"
documentation = "https://docs.rs/cpzkp"
edition = "2021"
homepage = "https://yourusername.github.io/cpzkp"
keywords = ["cryptography", "zero-knowledge", "zkp", "authentication", "security"]
license = "MIT"
name = "cpzkp"
readme = "README.md"
repository = "https://github.com/yourusername/cpzkp"
version = "0.1.0"

[features]
curve25519 = ["curve25519-dalek"]
default = ["scalar"]
ecc = []
ethereum = ["ethers", "secp256k1"]
python = ["pyo3"]
scalar = []
wasm = ["wasm-bindgen"]

[dependencies]
# Core dependencies
num = "0.4"
num-bigint = "0.4"
rand = "0.8"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
thiserror = "1.0"

# Optional dependencies
clap = {version = "4.4", features = ["derive"]}
curve25519-dalek = {version = "4.1", optional = true}
ethers = {version = "2.0", optional = true}
pyo3 = {version = "0.20", optional = true, features = ["auto-initialize"]}
secp256k1 = {version = "0.27", optional = true}
wasm-bindgen = {version = "0.2", optional = true}

[dev-dependencies]
criterion = "0.5"
maturin = "1.3"
mdbook = "0.4"
mdbook-mermaid = "0.12"
proptest = "1.3"
wasm-pack = "0.12"

[[bench]]
harness = false
name = "zkp_benchmarks"

[[bin]]
name = "cpzkp"
path = "src/bin/cli.rs"

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]

[package.metadata.docs.rs]
features = ["scalar", "ecc", "curve25519", "wasm", "python", "ethereum"]
targets = ["x86_64-unknown-linux-gnu"]
