[package]
authors = ["Your Name <your.email@example.com>"]
description = "A Zero-Knowledge Proof Authentication Library"
edition = "2021"
license = "MIT"
name = "zkp_auth"
repository = "https://github.com/yourusername/zkp_auth"
version = "0.1.0"

[dependencies]
log = "0.4"
num = "0.4"
num-bigint = "0.4"
rand = "0.8"
thiserror = "1.0"

[dev-dependencies]
criterion = "0.4"
proptest = "1.0"

[features]
bench = []
default = []

[[bench]]
harness = false
name = "zkp_operations"

[lib]
bench = false # Disable default benchmarking in favor of criterion
