[package]
authors = ["Your Name <your.email@example.com>"]
categories = ["cryptography", "authentication"]
description = "A Zero-Knowledge Proof Authentication Library"
edition = "2021"
keywords = ["cryptography", "zero-knowledge", "authentication", "security"]
license = "MIT"
name = "zkp_auth"
repository = "https://github.com/yourusername/zkp_auth"
version = "0.1.0"

[dependencies]
log = {version = "0.4", features = ["std"]}
num = "0.4"
num-bigint = {version = "0.4", features = ["rand"]}
rand = {version = "0.8", features = ["std", "getrandom"]}
thiserror = "1.0"

[dev-dependencies]
criterion = {version = "0.4", features = ["html_reports"]}
env_logger = "0.10"
proptest = "1.0"
test-log = "0.2"

[features]
bench = []
default = []

[[bench]]
harness = false
name = "zkp_operations"

[lib]
bench = false # Disable default benchmarking in favor of criterion

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = 3
panic = 'abort'

[profile.dev]
debug = true
opt-level = 0
