[package]
edition = "2021"
name = "cpzkp-webapp"
version = "0.1.0"

[dependencies]
cpzkp = {path = "../..", features = ["wasm"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
wasm-bindgen = "0.2"
web-sys = {version = "0.3", features = ["console"]}
yew = "0.20"
